# Generated by Django 5.2.4 on 2025-08-03 22:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('subscriptions', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, verbose_name='Пользователь')),
                ('email', models.EmailField(blank=True, max_length=40, verbose_name='Почта')),
                ('invoice_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='ID счета')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('success', 'Оплачен'), ('failed', 'Ошибка оплаты')], default='pending', max_length=20, verbose_name='Статус')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('extra_field', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='PaymentItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_type', models.CharField(choices=[('game', 'Игра'), ('subscription_service', 'Сервис подписки')], default='game', max_length=20, verbose_name='Тип продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_payment', to='games.game', verbose_name='Игра')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.payment', verbose_name='Платеж')),
                ('subscription_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payment', to='subscriptions.subscriptionservice', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Элемент платежа',
                'verbose_name_plural': 'Элементы платежа',
            },
        ),
    ]
