# Generated by Django 5.2.4 on 2025-08-03 22:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consoles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тип консоли',
                'verbose_name_plural': 'Типы консолей',
            },
        ),
        migrations.CreateModel(
            name='SeoMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.TextField(blank=True, null=True, verbose_name='Код Яндекс Метрики')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('meta', models.CharField(blank=True, max_length=250, null=True, verbose_name='Мета')),
            ],
            options={
                'verbose_name': 'SEO Метрика',
                'verbose_name_plural': 'SEO Метрики',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('level', models.CharField(blank=True, choices=[('Essential', 'Essential'), ('Extra', 'Extra'), ('Deluxe', 'Deluxe')], max_length=70, null=True, verbose_name='Уровень подписки')),
                ('image', models.FileField(blank=True, null=True, upload_to='subscription_images/', verbose_name='Изображение')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступна ли подписка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('consoles', models.ManyToManyField(related_name='subscriptions', to='subscriptions.consoles', verbose_name='Консоли')),
            ],
            options={
                'verbose_name': 'Сервис подписки',
                'verbose_name_plural': 'Сервисы подписок',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('months', models.IntegerField(verbose_name='Количество месяцев')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('subscription_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='subscriptions.subscriptionservice', verbose_name='Сервис подписки')),
            ],
            options={
                'verbose_name': 'Период подписки',
                'verbose_name_plural': 'Периоды подписки',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=40, verbose_name='Почта')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('subscription_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='subscriptions.subscriptionperiod', verbose_name='Период подписки')),
                ('subscription_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='subscriptions.subscriptionservice', verbose_name='Сервис подписки')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
