# Generated by Django 5.2.4 on 2025-08-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seometric',
            name='keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова'),
        ),
    ]
