# Generated by Django 5.2.4 on 2025-08-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_seometric_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seometric',
            name='description',
        ),
        migrations.RemoveField(
            model_name='seometric',
            name='keywords',
        ),
        migrations.AlterField(
            model_name='seometric',
            name='meta',
            field=models.TextField(blank=True, null=True, verbose_name='Мета'),
        ),
    ]
