# Generated by Django 5.2.4 on 2025-08-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_remove_seometric_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seometric',
            name='meta',
        ),
    ]
