# Generated by Django 5.2.4 on 2025-08-03 22:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('publisher', models.CharField(blank=True, max_length=50, null=True, verbose_name='Издатель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Издатель',
                'verbose_name_plural': 'Издатели',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=500, verbose_name='Название')),
                ('url_u', models.CharField(blank=True, max_length=255, verbose_name='URL_U')),
                ('url_t', models.CharField(blank=True, max_length=255, verbose_name='URL_T')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='Slug')),
                ('main_image_url', models.CharField(max_length=255, verbose_name='Главное изображение(URL)')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('categories', models.ManyToManyField(blank=True, related_name='category_games', to='games.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(blank=True, verbose_name='Вопрос')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='games.game')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=255, verbose_name='URL изображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='games.game')),
            ],
            options={
                'verbose_name': 'Изображения',
                'verbose_name_plural': 'Изображение',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('consoles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.consoles', verbose_name='Консоли')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='subtitle',
            field=models.ManyToManyField(blank=True, related_name='subtitle_games', to='games.language', verbose_name='Субтитры'),
        ),
        migrations.AddField(
            model_name='game',
            name='voice_acting',
            field=models.ManyToManyField(blank=True, related_name='voice_acting_games', to='games.language', verbose_name='Озвучки'),
        ),
        migrations.AddField(
            model_name='game',
            name='publishers',
            field=models.ManyToManyField(blank=True, related_name='publisher_game', to='games.publisher', verbose_name='Издатель'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(blank=True, choices=[('with_activation', 'С активацией'), ('without_activation', 'Без активаций')], default='without_activation', max_length=70, verbose_name='Тип активации')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sale_unit', models.CharField(blank=True, choices=[('price', 'Рубли'), ('percent', 'Проценты')], default='percent', max_length=70, null=True, verbose_name='Единица')),
                ('sale_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сума или Процент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('consoles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.consoles', verbose_name='Консоли')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='games.game')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
                'unique_together': {('game', 'consoles', 'payment_type')},
            },
        ),
    ]
