# Generated by Django 5.2.4 on 2025-08-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='main_image_url',
            field=models.CharField(max_length=1000, verbose_name='Главное изображение(URL)'),
        ),
    ]
