# Generated by Django 5.2.4 on 2025-08-19 23:00

import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_main_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='main_image_url',
            field=models.ImageField(max_length=500, upload_to=games.models.game_main_image_path, verbose_name='Главное изображение(URL)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Название'),
        ),
    ]
