# Generated by Django 5.2.4 on 2025-08-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_main_image_url_alter_game_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название'),
        ),
    ]
