# Generated by Django 5.2.4 on 2025-11-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='articule',
            field=models.CharField(blank=True, null=True, verbose_name='Артикул'),
        ),
    ]
